FROM althack/ros2:humble-full

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone 
USER root

# install git
RUN apt update && apt install -y git

WORKDIR /workspace
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc 
RUN apt update && apt install -y ros-humble-rmw-cyclonedds-cpp ros-humble-rosidl-generator-dds-idl

# 配置代理环境变量（使用 host.docker.internal 访问宿主机）
ENV http_proxy=http://host.docker.internal:54009
ENV https_proxy=http://host.docker.internal:54009
ENV no_proxy=localhost,127.0.0.1

CMD [ "/bin/bash" ]