#!/bin/bash
# Colcon vs CMake 编译对比演示

echo "=============================================="
echo "  Colcon vs CMake 编译内容对比演示"
echo "=============================================="

# 颜色定义
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo -e "${BLUE}📂 1. Colcon 编译的目录结构${NC}"
echo "=============================================="
echo "当你运行: colcon build"
echo ""
echo "生成的目录结构:"
echo "example/"
echo "├── build/                    ← 构建临时文件"
echo "│   └── unitree_ros2_example/ ← 每个包一个子目录"
echo "│       ├── CMakeCache.txt"
echo "│       ├── Makefile"
echo "│       ├── *.o 文件"
echo "│       └── 可执行文件 (临时)"
echo "│"
echo "├── install/                  ← 最终安装位置 ⭐"
echo "│   ├── setup.bash            ← 环境脚本"
echo "│   └── unitree_ros2_example/"
echo "│       ├── lib/              ← 最终的可执行文件在这里"
echo "│       │   └── unitree_ros2_example/"
echo "│       │       ├── read_low_state"
echo "│       │       └── custom_sensor_reader"
echo "│       └── share/            ← 配置文件"
echo "│"
echo "└── src/                      ← 源代码"
echo ""

echo -e "${BLUE}📂 2. 纯 CMake 编译的目录结构${NC}"
echo "=============================================="
echo "当你运行: mkdir build && cd build && cmake .. && make"
echo ""
echo "生成的目录结构:"
echo "my_project/"
echo "├── build/                    ← 所有构建文件都在这里"
echo "│   ├── CMakeCache.txt"
echo "│   ├── Makefile"
echo "│   ├── *.o 文件"
echo "│   └── my_program            ← 可执行文件直接在这"
echo "│"
echo "└── src/                      ← 源代码"
echo ""

echo -e "${YELLOW}🔍 3. 关键区别${NC}"
echo "=============================================="
echo ""
echo -e "${GREEN}✓ Colcon 方式:${NC}"
echo "  - 编译产物在: build/package_name/"
echo "  - 可执行文件安装到: install/package_name/lib/"
echo "  - 自动生成环境脚本: install/setup.bash"
echo "  - 支持多个包的依赖关系"
echo ""
echo -e "${GREEN}✓ CMake 方式:${NC}"
echo "  - 编译产物在: build/"
echo "  - 可执行文件直接在: build/"
echo "  - 需要手动设置环境变量"
echo "  - 适合单一项目"
echo ""

echo -e "${RED}⚠️  4. 为什么不要混用?${NC}"
echo "=============================================="
echo ""
echo "❌ 如果在 Colcon 项目中直接用 CMake:"
echo ""
echo "cd example/build/unitree_ros2_example"
echo "cmake ../../src"
echo "make"
echo ""
echo "会导致:"
echo "  1. 路径混乱 - Colcon 期望的路径被破坏"
echo "  2. 安装失败 - 文件不在 install/ 目录"
echo "  3. 环境变量错误 - setup.bash 失效"
echo "  4. 依赖问题 - ROS2 依赖无法正确解析"
echo ""

echo -e "${GREEN}✅ 5. 正确的使用方式${NC}"
echo "=============================================="
echo ""
echo "对于 ROS2 项目 (unitree_ros2):"
echo ""
echo -e "  ${BLUE}cd /home/weeq/unitree_ros2/example${NC}"
echo -e "  ${BLUE}colcon build${NC}"
echo -e "  ${BLUE}source install/setup.bash${NC}"
echo -e "  ${BLUE}ros2 run unitree_ros2_example custom_sensor_reader${NC}"
echo ""
echo "不要运行:"
echo -e "  ${RED}cd build/unitree_ros2_example${NC}"
echo -e "  ${RED}cmake ../../src${NC}  ❌"
echo ""

echo -e "${BLUE}📝 6. 编译产物是否相同?${NC}"
echo "=============================================="
echo ""
echo "理论上: 相同"
echo "  - 都是 ELF 可执行文件"
echo "  - 都链接相同的库"
echo "  - 都能运行"
echo ""
echo "实践中: 位置和使用方式不同"
echo "  - Colcon: install/lib/unitree_ros2_example/program"
echo "  - CMake:  build/program"
echo ""

echo -e "${YELLOW}💡 7. 查看实际编译的文件${NC}"
echo "=============================================="
echo ""

if [ -d "/home/weeq/unitree_ros2/example/build/unitree_ros2_example" ]; then
    echo "Colcon 编译的可执行文件:"
    ls -lh /home/weeq/unitree_ros2/example/build/unitree_ros2_example/*.* 2>/dev/null | grep -E "rwx" | head -5
    echo ""
fi

if [ -d "/home/weeq/unitree_ros2/example/install/unitree_ros2_example/lib" ]; then
    echo "Colcon 安装的可执行文件:"
    ls -lh /home/weeq/unitree_ros2/example/install/unitree_ros2_example/lib/unitree_ros2_example/ 2>/dev/null | head -5
    echo ""
fi

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}总结: 在 ROS2 项目中,${NC}"
echo -e "${GREEN}始终使用 colcon build!${NC}"
echo -e "${GREEN}========================================${NC}"
